### ISSUE TITLE
No github tag or release for v0.2.2

### ISSUE THREAD

**Issue by scottj97** [tbekolay/pytest-cram#14]
There is a release 0.2.2 on PyPi but no tag in the git repo and no [release](https://github.com/tbekolay/pytest-cram/releases) here on github.

**Comment by tbekolay** [comment]
You're right, not sure why I didn't do that! The tag [exists now](https://github.com/tbekolay/pytest-cram/releases/tag/v0.2.2). Thanks for pointing this out!
