### ISSUE TITLE
Run CI on Windows

### ISSUE THREAD

**Issue by kynan** [tbekolay/pytest-cram#4]
Following up on #3, which is now resolved, I think it would be useful to also test pytest-cram on Windows e.g. using [AppVeyor](https://ci.appveyor.com). I assume like myself you don't use Windows and have no ready access to a Windows box to test manually. kynan/nbstripout#24 is now resolved and we have [CI successfully running on Windows](https://ci.appveyor.com/project/kynan/nbstripout/build/1.0.11).

Have a peek at nbstripout's [appveyor.yml](https://github.com/kynan/nbstripout/blob/master/appveyor.yml) or the one from [pre-commit](https://github.com/pre-commit/pre-commit/blob/master/appveyor.yml) (which was my inspiration) for a starting point. I'd send you a pr, but obviously I wouldn't be able to set up the necessary AppVeyor webhook.

**Comment by tbekolay** [comment]
You are correct, I don't have access to a Windows box. I'll set up an AppVeyor webhook shortly!

**Comment by kynan** [comment]
Excellent, thanks!
